engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
    exclude_fingerprints:
      - fd9823136629e6b402bc35e57f6b7cb5 # https://github.com/stevegrunwell/mcavoy/issues/21
  fixme:
    enabled: true
ratings:
  paths:
  - "**.php"
exclude_paths:
- tests/*
