language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - WP_VERSION=master
    - WP_VERSION=4.4

before_script:
  - composer install --prefer-source
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - ./vendor/bin/test-reporter

cache:
  directories:
    - vendor/

notifications:
  email: false